
#pragma once

typedef enum _COMMON_ERROR
{
    COMMON_ERROR_DEFAULT = -1,
    COMMON_ERROR_SUCCESS,
    COMMON_ERROR_GET_MODULE_HANDLE_FAILED,
    COMMON_ERROR_GET_PROC_ADDRESS_FAILED,
    COMMON_ERROR_CREATE_DIRECTORY_FAILED,
    COMMON_ERROR_GET_VERSION_FAILED,
    COMMON_ERROR_INVALID_PARAMETER,
    COMMON_ERROR_NOT_FOUND,
    COMMON_ERROR_SET_FILE_POINTER_FAILED,
    COMMON_ERROR_HANDLE_INFO_ERROR,
    COMMON_ERROR_INSUFFICIENT_RESOURCE,
    COMMON_ERROR_DECRYPT_BUFFER_FAILED,
    COMMON_ERROR_ENCRYPT_BUFFER_FAILED,
    COMMON_ERROR_WRITE_FILE_FAILED,
    COMMON_ERROR_FLUSH_FILE_FAILED
} COMMON_ERROR, *PCOMMON_ERROR;
